---
title: "Identification of cutting model parameters for a flat milling process"
author: "Thomas M. Rudolf"
email: "thomas.rudolf@itam.mx"
affiliations: "Instituto Tecnológico Autónomo de México - ITAM"
date: "2024-03-26"
format: pdf
editor: visual
---

#abstract\
Process monitoring for milling operation is widely used to ensure product quality and optimize costs. Detecting a worn tool on time can prevent tool breakage and quality issues. Therefore, the observation of wear status is crucial in process monitoring. A typical approach to tool wear detection is the monitoring of required energy and resulting cutting forces. The forces are based on the removed volume and the material characteristics. In the first part, the author explains different cutting force models and their corresponding parameters, their impact on modeled forces.\
The force is typically defined by $F_c = k_{c1.1} b h^{1-m_c}$, with parameters specific cutting force $k_{c1.1}$ and increasing value of the specific cutting force$(1-m_c)$, $b$ and $h$ are the geometric values of the removed material, width and height, respectively. The significance of the parameters $k_{c1.1}$ and $(1-m_c)$ are the topic of discussion. Although there are known values for specific materials, each working batch has slightly different values which results in changing force values for the same machining process. The presented approach uses a Bayesian method to detect and identify the current values based on former knowledge. Initial distribution for both parameters are defined, and their selection explained. Then, new data is acquired during the first cuts and the resulting distribution is calculated.\
Keywords: Gibbs Sampler, direct Bayesian methods, milling process monitoring
